import { db } from '@/db';
import { courses } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const sampleCourses = [
        {
            title: 'Intro to Python',
            slug: 'intro-to-python',
            description: 'Learn Python programming from scratch. Perfect for beginners with no coding experience.',
            instructorId: 2,
            schoolId: 1,
            category: 'Programming',
            thumbnail: 'https://picsum.photos/seed/python/400/300',
            durationHours: 40,
            level: 'BEGINNER',
            price: 49.99,
            enrolledCount: 45,
            rating: 4.7,
            createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Web Development Bootcamp',
            slug: 'web-development-bootcamp',
            description: 'Master HTML, CSS, JavaScript, and modern web frameworks. Build real-world projects.',
            instructorId: 3,
            schoolId: 2,
            category: 'Programming',
            thumbnail: 'https://picsum.photos/seed/webdev/400/300',
            durationHours: 80,
            level: 'INTERMEDIATE',
            price: 79.99,
            enrolledCount: 67,
            rating: 4.9,
            createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Physics 101',
            slug: 'physics-101',
            description: 'Introduction to physics covering mechanics, energy, and motion with hands-on experiments.',
            instructorId: 4,
            schoolId: 3,
            category: 'Science',
            thumbnail: 'https://picsum.photos/seed/physics/400/300',
            durationHours: 50,
            level: 'BEGINNER',
            price: 59.99,
            enrolledCount: 38,
            rating: 4.6,
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Advanced Chemistry',
            slug: 'advanced-chemistry',
            description: 'Deep dive into organic chemistry, reaction mechanisms, and laboratory techniques.',
            instructorId: 4,
            schoolId: 3,
            category: 'Science',
            thumbnail: 'https://picsum.photos/seed/chemistry/400/300',
            durationHours: 60,
            level: 'ADVANCED',
            price: 89.99,
            enrolledCount: 22,
            rating: 4.8,
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Calculus Fundamentals',
            slug: 'calculus-fundamentals',
            description: 'Master derivatives, integrals, and their applications. Perfect for AP Calculus prep.',
            instructorId: 2,
            schoolId: 1,
            category: 'Mathematics',
            thumbnail: 'https://picsum.photos/seed/calculus/400/300',
            durationHours: 55,
            level: 'INTERMEDIATE',
            price: 69.99,
            enrolledCount: 52,
            rating: 4.7,
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Statistics Made Easy',
            slug: 'statistics-made-easy',
            description: 'Learn statistical analysis, probability, and data interpretation from basics.',
            instructorId: 3,
            schoolId: 2,
            category: 'Mathematics',
            thumbnail: 'https://picsum.photos/seed/statistics/400/300',
            durationHours: 45,
            level: 'BEGINNER',
            price: 54.99,
            enrolledCount: 41,
            rating: 4.5,
            createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'English Literature',
            slug: 'english-literature',
            description: 'Explore classic and contemporary literature with critical analysis techniques.',
            instructorId: 2,
            schoolId: 1,
            category: 'Language',
            thumbnail: 'https://picsum.photos/seed/literature/400/300',
            durationHours: 48,
            level: 'INTERMEDIATE',
            price: 59.99,
            enrolledCount: 35,
            rating: 4.6,
            createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            title: 'Creative Writing Workshop',
            slug: 'creative-writing-workshop',
            description: 'Develop your storytelling skills through fiction, poetry, and creative exercises.',
            instructorId: 3,
            schoolId: 2,
            category: 'Language',
            thumbnail: 'https://picsum.photos/seed/writing/400/300',
            durationHours: 35,
            level: 'BEGINNER',
            price: 49.99,
            enrolledCount: 29,
            rating: 4.4,
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(courses).values(sampleCourses);
    
    console.log('✅ Courses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});