import { db } from '@/db';
import { posts } from '@/db/schema';

async function main() {
    const now = new Date();
    const samplePosts = [
        {
            userId: 2,
            schoolId: 1,
            type: 'ARTICLE',
            title: 'Understanding Quadratic Equations: A Complete Guide',
            content: 'Quadratic equations are fundamental in algebra and have numerous real-world applications. In this comprehensive guide, we explore the standard form ax² + bx + c = 0, various methods of solving including factoring, completing the square, and the quadratic formula. We also discuss the discriminant and its significance in determining the nature of roots. Understanding these concepts is crucial for advanced mathematics and physics.',
            mediaUrls: null,
            pollOptions: null,
            fileUrls: null,
            viewCount: 187,
            knowledgePoints: 50,
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 3,
            schoolId: 1,
            type: 'ARTICLE',
            title: 'The Mitochondria: Powerhouse of the Cell Explained',
            content: 'Mitochondria play a crucial role in cellular respiration and energy production. This article delves into the structure of mitochondria, including the inner and outer membranes, cristae, and matrix. We examine the process of ATP synthesis through oxidative phosphorylation and the electron transport chain. Understanding mitochondrial function is essential for comprehending cellular metabolism and various diseases linked to mitochondrial dysfunction.',
            mediaUrls: ['https://example.com/mitochondria-diagram.jpg'],
            pollOptions: null,
            fileUrls: null,
            viewCount: 234,
            knowledgePoints: 70,
            createdAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 4,
            schoolId: 2,
            type: 'ARTICLE',
            title: 'Newton\'s Laws of Motion: From Theory to Practice',
            content: 'Sir Isaac Newton\'s three laws of motion form the foundation of classical mechanics. This detailed exploration covers the first law (inertia), second law (F=ma), and third law (action-reaction pairs). We provide numerous examples from everyday life and engineering applications, demonstrating how these principles govern everything from rocket propulsion to vehicle safety systems. Includes problem-solving strategies and common misconceptions to avoid.',
            mediaUrls: null,
            pollOptions: null,
            fileUrls: null,
            viewCount: 201,
            knowledgePoints: 80,
            createdAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 6 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 5,
            schoolId: 2,
            type: 'STUDY_MATERIAL',
            title: 'Advanced Calculus Notes: Limits, Derivatives, and Integrals',
            content: 'Comprehensive study material covering the fundamental concepts of calculus. This document includes detailed explanations of limits and continuity, differentiation techniques (chain rule, product rule, quotient rule), applications of derivatives, integration methods, and the fundamental theorem of calculus. Perfect for exam preparation with solved examples and practice problems.',
            mediaUrls: null,
            pollOptions: null,
            fileUrls: ['https://example.com/calculus-notes.pdf', 'https://example.com/practice-problems.pdf'],
            viewCount: 156,
            knowledgePoints: 90,
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 6,
            schoolId: 3,
            type: 'STUDY_MATERIAL',
            title: 'Organic Chemistry Reaction Mechanisms Handbook',
            content: 'Complete reference guide for organic chemistry reactions including nucleophilic substitution (SN1, SN2), elimination reactions (E1, E2), electrophilic addition, and free radical reactions. Features detailed mechanism drawings, stereochemistry considerations, and reaction conditions. Essential resource for chemistry students and competitive exam preparation.',
            mediaUrls: null,
            pollOptions: null,
            fileUrls: ['https://example.com/organic-chem-handbook.pdf', 'https://example.com/reaction-flowchart.pdf'],
            viewCount: 178,
            knowledgePoints: 100,
            createdAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 7,
            schoolId: 1,
            type: 'QUESTION',
            title: 'How do I solve this trigonometry problem?',
            content: 'I\'m stuck on this problem: If sin(θ) = 3/5 and θ is in the second quadrant, find the value of cos(θ) and tan(θ). I know sin²(θ) + cos²(θ) = 1, but I\'m not sure how to determine the sign of cos(θ) in the second quadrant. Can someone explain the step-by-step solution?',
            mediaUrls: null,
            pollOptions: null,
            fileUrls: null,
            viewCount: 89,
            knowledgePoints: 0,
            createdAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 8,
            schoolId: 2,
            type: 'QUESTION',
            title: 'Need help understanding photosynthesis process',
            content: 'I\'m preparing for my biology exam and struggling with the light-dependent and light-independent reactions. Can someone explain: 1) What happens in the thylakoid membrane? 2) How is ATP produced? 3) What\'s the role of NADPH? 4) How does the Calvin cycle work? Any diagrams or simple explanations would be really helpful!',
            mediaUrls: null,
            pollOptions: null,
            fileUrls: null,
            viewCount: 102,
            knowledgePoints: 10,
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 2,
            schoolId: 1,
            type: 'PHOTO_VIDEO',
            title: 'Our Chemistry Lab Experiment: Titration Demo',
            content: 'Check out our acid-base titration experiment today! We successfully determined the unknown concentration of HCl using standardized NaOH solution. The color change with phenolphthalein indicator was perfect. Swipe to see our setup, procedure, and results. #ChemistryLab #Titration',
            mediaUrls: ['https://example.com/lab-setup.jpg', 'https://example.com/titration-video.mp4', 'https://example.com/results-graph.jpg'],
            pollOptions: null,
            fileUrls: null,
            viewCount: 145,
            knowledgePoints: 30,
            createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 3,
            schoolId: 1,
            type: 'CELEBRATE',
            title: 'Just got selected for National Science Olympiad! 🎉',
            content: 'I\'m thrilled to announce that I\'ve been selected to represent our school at the National Science Olympiad! All those late-night study sessions and practice tests finally paid off. Special thanks to my teachers and classmates for their support. Looking forward to this amazing opportunity! #NSO2024 #ScienceOlympiad #Proud',
            mediaUrls: ['https://example.com/selection-letter.jpg'],
            pollOptions: null,
            fileUrls: null,
            viewCount: 89,
            knowledgePoints: 0,
            createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        },
        {
            userId: 4,
            schoolId: 2,
            type: 'POLL',
            title: 'Which programming language should I learn first?',
            content: 'I\'m starting my coding journey and want to know which language is best for beginners. I\'m interested in web development and app creation. What would you recommend and why? Your votes and comments will help me decide!',
            mediaUrls: null,
            pollOptions: ['Python - Easy syntax and versatile', 'JavaScript - Essential for web dev', 'Java - Strong fundamentals', 'C++ - Better for understanding basics'],
            fileUrls: null,
            viewCount: 167,
            knowledgePoints: 20,
            createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(posts).values(samplePosts);
    
    console.log('✅ Posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});